name: Build

on:
  workflow_call:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build_release:
    name: Build release binaries
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: mymindstorm/setup-emsdk@v11
      if: matrix.os == 'ubuntu-latest'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G"Ninja"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -t package

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Configure CMake with EMCC
      if: matrix.os == 'ubuntu-latest'
      run: emcmake cmake -B ${{github.workspace}}/build-emcc -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build with EMCC
      if: matrix.os == 'ubuntu-latest'
      run: cmake --build ${{github.workspace}}/build-emcc --config ${{env.BUILD_TYPE}} -t package

    - uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        name: console-build
        path: ${{github.workspace}}/build/*.zip

    - uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        name: web-build
        path: ${{github.workspace}}/build-emcc/*.zip

    - uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        name: windows-build
        path: ${{github.workspace}}/build/*.zip
