name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    uses: ./.github/workflows/build.yml

  create_release:
    needs: [ build_release ]
    name: Create release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2

    - name: Make directory for extraction
      run: mkdir ${{github.workspace}}/web-extract

    - name: Extract web version
      working-directory: ${{github.workspace}}/web-extract
      run: unzip ../web-build/*web*.zip

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/web-extract/web

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Rename files
      run: |
        mkdir output
        mv console-build/*.zip output/wordle-solver-linux-${{ steps.get_version.outputs.VERSION }}.zip
        mv macos-build/*.zip output/wordle-solver-mac-${{ steps.get_version.outputs.VERSION }}.zip
        mv web-build/*chrome*.zip output/wordle-solver-chrome-extension-${{ steps.get_version.outputs.VERSION }}.zip
        mv web-build/*web*.zip output/wordle-solver-web-${{ steps.get_version.outputs.VERSION }}.zip
        mv windows-build-win32/*.zip output/wordle-solver-win32-${{ steps.get_version.outputs.VERSION }}.zip
        mv windows-build-win64/*.zip output/wordle-solver-win64-${{ steps.get_version.outputs.VERSION }}.zip

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: output/*

