name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    uses: ./.github/workflows/build.yml

  create_release:
    needs: [ build_release ]
    name: Create release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          console-build/*
          web-build/*
          windows-build/*
          macos-build/*
